<<UNIX_TECHS

/////////////////////////////////////////////////
	  UNIX TECHS
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\







 현재 디렉토리에서 리커시브로 빈디렉토리 찾기 명령어
 find . -type d -empty -print

 현재 디렉토리에서 리커시브로 빈디렉토리 찾아서 지우기 명령어
 find . -type d -empty -delete <--- 이명령어 조심
디렉토리명에 심볼릭링크는 안됨


 SHIFT+v > select > Register COPY "+y or "*p  
 Register PASTE "+p or "*p

:bnext <- buffer command 
:buffer
:split
:h buffer-list

$ killall -HUP transmission-da
Or:
$ pkill -HUP transmission-da


https://pimylifeup.com/raspberry-pi-torrentbox/
sudo service transmission-daemon reload

watch -n 2 "vcgencmd measure_temp"

vim 속도때문에 syntax on 제거. 색깔 필요시 수동 :syn on

CRON 확인
로그에 올라오지 않는경우
grep CRON /var/log/syslog 
ps -ef | grep cron | grep -v grep
시간규칙 9-12는 안된다. 9,10,11,12로 사용할것
위의 규칙만 지키면 로그에 올라온다(몇분기다려야함)
가능하면cron reload/restart 명령으로 올려봄 (확실하지않음)

로그에는 올라오나 작동하지 않는경우:
cron 명령어 및 패스는 절대경로로 홈 ~

퍼미션은 가능하면 755로 한다. 꼭777은아님
크론명령줄에 * * * /bin/bash cmd 안붙여도됨


nano >

CTRL+SHIFT+6 Mark Set
CTRL+K cut line / cut
CTRL+U paste

dpkg >
sudo dpkg --get-selections | grep ufw



{ 보안정책 }

(고정아이피) -> 네트워크 속도가 약간 빨라진다.

sudo nano /etc/network/interfaces

eth0 포함 라인 주석처리하고 4라인 추가한다.

#iface eth0 inet manual
iface eth0 inet static
address 192.168.1.11
netmask 255.255.255.0
gateway 192.168.1.1




sudo vi /etc/ssh/sshd_config
항목 중
Port 1024
PermitRootLogin no
저장하고 SSH 재시작
sudo service ssh restart


iptable >



$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination 
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

(iptables 정책을 파일로 얻기.)
$ sudo iptables-save > iptables_rules
$ cat iptables_rules
# Generated by iptables-save v1.4.14 on Sun Sep  6 22:44:51 2015
*filter
:INPUT ACCEPT [353:26718]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [181:18458]
COMMIT
# Completed on Sun Sep  6 22:44:51 2015
정책 파일 수정.

$ vi iptables_rules
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT 
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT 
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
# Allow ICMP packets necessary for MTU path discovery
#-A INPUT -p icmp --icmp-type fragmentation-needed -j ACCEPT
# Allow echo request
#-A INPUT -p icmp --icmp-type 8 -j ACCEPT
-A INPUT -j DROP 
COMMIT

(iptables 정책 적용) *** -> 부팅시 적용시켜줘야한다.
sudo iptables-restore < iptables_rules

autostartup.sh 에서 적용시키거나 아래 스크립트 처럼.

(다른 방법)
/etc/firewall.conf >

sudo -s

iptables-save > /etc/firewall.conf

[INCLUDE ON BOOT]
echo '#!/bin/sh' > /etc/network/if-up.d/iptables 
echo "iptables-restore < /etc/firewall.conf" >> /etc/network/if-up.d/iptables
chmod +x /etc/network/if-up.d/iptables

[SAVE ON SHUTDOWN/REBOOT]
echo '#!/bin/sh' > /etc/network/if-down.d/iptables 
echo "iptables-save > /etc/firewall.conf" >> /etc/network/if-down.d/iptables
chmod +x /etc/network/if-down.d/iptables



log >

vi /etc/rsyslog.conf

Uncomment 
# cron.*  /var/log/cron.log

(default setting)
#cron.*             /var/log/cron.log
daemon.*            -/var/log/daemon.log
kern.*              -/var/log/kern.log
user.*              -/var/log/user.log

(Restart rsyslog)
sudo /etc/init.d/rsyslog restart

vi multiple comment >

v or SHIFT+v, VISUAL BLOCK select, :s/^/#/ 
커서가 있는행까지 채워진다.

행번호로 지정하는 방법
:10,20s/^/#  <-- Comment
:10,20s/^#/  <-- Uncomment

command_line=(
"sudo /etc/init.d/networking restart"
"sudo /etc/init.d/networking reload"
"sudo /etc/init.d/cron restart"
"sudo /etc/init.d/samba restart"
"sudo /etc/init.d/apache2 restart"
"sudo service transmission-daemon restart"
"ssudo vi /etc/network/interfaces"	
)

#echo "array=${command_line[@]}"
#printf "%s\n" "${command_line[@]}"




<<FOR_1
for value in "{$command_line[@]}" ; do
	echo $command_line
done
FOR_1

#<<FOR_2
for ((i=0; i < ${#command_line[@]}; i++)) ; do
	printf "%d. %s\n" "$(($i+1))" "${command_line[$i]}"
done
#FOR_2

<<FOR_3
for index  in ${!command_line[*]} ; do
	printf "[%d]-> %s\n" "$(($index+1))"  "${command_line[$index]}"
done
FOR_3



RPi install problem) ex)mysql  
sudo apt-get install -f
sudo apt-get install --reinstall perl-base





라즈베리파이에서는 아직...
sudo apt-get install python-dev
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
sudo pip install –upgrade $TF_BINARY_URL











youtube 관련)

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

sudo pip install --upgrade youtube_dl

brew install youtube-dl









\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
		                     Try Everything !!!			
/////////////////////////////////////////////////

UNIX_TECHS